[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
lollys_lotto = "EQHT3TFXS3hBMzSpJiKb84sHE7iBXnYBpWvQTU8r91m6"

[programs.localnet]
lollys_lotto = "EQHT3TFXS3hBMzSpJiKb84sHE7iBXnYBpWvQTU8r91m6"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "https://devnet.helius-rpc.com/?api-key=7c45b0ae-2e65-4ef0-b68c-defcf9f5b581"
cluster = "http://localhost:8899"
wallet = "/Users/0xabstracted/Lolly/LollyLottoTS/.keys/1o1ohFR7M25XktNXAsbnDbvserNoFkrFLdA9916EGWw.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test.validator]
url = "https://devnet.helius-rpc.com/?api-key=7c45b0ae-2e65-4ef0-b68c-defcf9f5b581"
# url = "http://localhost:8899"

[test]
startup_wait = 15000
shutdown_wait = 2000
upgradeable = false


[[test.validator.clone]] # sb devnet oracle programID
address = "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"

[[test.validator.clone]] # sb devnet oracle IDL
address = "Fi8vncGpNKbq62gPo56G4toCehWNy77GgqGkTaAF5Lkk"

[[test.validator.clone]] # sb devnet oracle SbState
address = "CyZuD7RPDcrqCGbNvLCyqk6Py9cEZTKmNKujfPi3ynDd"

[[test.validator.clone]] # sb devnet oracle tokenVault
address = "7hkp1xfPBcD2t1vZMoWWQPzipHVcXeLAAaiGXdPSfDie"

[[test.validator.clone]] # sb devnet attestation programID
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

[[test.validator.clone]] # sb devnet attestation IDL
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"

[[test.validator.clone]] # sb devnet programState
address = "5MFs7RGTjLi1wtKNBFRtuLipCkkjs4YQwRRU9sjnbQbS"